t_main_article:
    resource: "@TMainBundle/Resources/config/routing/article.yml"
    prefix:   /article

t_main_homepage:
    path:     /
    defaults: { _controller: TMainBundle:Default:index }

t_main_tarif:
    path:     /tarif
    defaults: { _controller: TMainBundle:Default:tarif }

t_main_contact:
    path:     /contact
    defaults: { _controller: TMainBundle:Default:contact }
